# Generated by Django 3.0.4 on 2020-03-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='images/'),
        ),
    ]
