# Generated by Django 3.0.4 on 2020-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200331_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='media/images/'),
        ),
    ]
